### ISSUE TITLE
Project milestones

### ISSUE THREAD

**Issue by bronwynagrios** [AstroDigital/modis-ingestor#3]
- [x] Friday Jan 6th - MVP
- [ ] Thursday January 12th - working group call to present format to a few interested parties, see #4.
- [ ] Friday January 27th - Blog posts, finalize landing page
- [ ] Tuesday January 31st - Launch
